name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Автодеплой на сервер
    runs-on: ubuntu-latest

    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v3

      - name: SSH + deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            if [ ! -d "/root/LezgianWebsiteBackend" ]; then
              cd /root
              git clone https://Topando:${{ secrets.GH_DEPLOY_TOKEN }}@github.com/Project-Restricted/Backend.git
            fi
            cd /root/LezgianWebsiteBackend
            git pull origin main
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --build